### ISSUE TITLE
why aren't my hooks not registered and triggered across all clients?

### ISSUE THREAD

**Issue by rdewolff** [matb33/meteor-collection-hooks#111]
Hi all

Wondering if it's possible to execute the hooks across all the connected clients?

Currently I registered my hooks (tried on client side and on client and server side) and want them to be triggered across all connected clients.

My goal is that when client 1 is updating a doc, all the clients connected clients will get an update and can act upon change.

Is that possible? Am I missing something here?

Thanks for your input!

Cheers!

**Comment by matb33** [comment]
That's not really what collection-hooks is meant for -- this is what Meteor does for you for free! Look into publish/subscribe etc in the docs: http://docs.meteor.com/

(Apologies in advance if I misunderstood your intent and you know of all this already)

**Comment by rdewolff** [comment]
Thanks for your quick answer. Yes I know we can do that with publish/subscribe.

But wouldn't that be a nice option for the meteor-collection-hooks ? IMHO that would be a great addition.

**Comment by matb33** [comment]
You could set-up client-side hooks to fire off a `Meteor.call` to a server method that then does the rebroadcasting to all clients. But really then you're just reinventing what Meteor is already doing, as it does something similar itself when you do an insert/update/remove etc.

I might still be misunderstanding what you're trying to accomplish, because honestly it doesn't make any sense to have the collection hooks do this work, especially since you're already dealing with mongo collections. You've observeChanges to act on updates, or even a plain old autorun wrapped around a find query on the client to act on updates there too. All the plumbing is there -- collection-hooks really doesn't make sense for this

**Comment by rdewolff** [comment]
Thanks @matb33 for the precisions and explanations. Gotta dig a bit deeper and check ```observeChanges```, seems like what I need!
