### ISSUE TITLE
Collection.direct.insert({}) not returning id as Collection.insert({}) does.

### ISSUE THREAD

**Issue by ernestorocha** [matb33/meteor-collection-hooks#86]
One can do that:
```
var id = Meteor.users.insert(data);
```
But when doing this:

```
var data2 = Meteor.users.direct.insert(data);
```

What actually is returned is the same insert params (data) plus a key called ``_id`` that has nothing to do with the newly created object Id on database.

What I was expecting was the same behavior. Is there a reason to not to return the same thing ?

**Comment by matb33** [comment]
This seems familiar... I feel like there's an open issue that highlights either the same thing or something similar. Anyway, looks like https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L95 `return _super.apply(collection, args);` is using `_super`, which in turn is pulled from the var `collection`, which is determined using `var collection = Meteor.isClient ? self : self._collection;`.

In the case of a direct operation, `collection` should actually always be `self` and not the underlying `self._collection`. In normal collection hooks usage, i.e. insert, update, remove, we target `self._collection` on the server so that the allow/deny rules have a chance to run.

So, this is indeed a bug, and a simple enough fix -- I'll get around to it shortly.

**Comment by matb33** [comment]
There it is, and I unfortunately let it slip: https://github.com/matb33/meteor-collection-hooks/issues/73

**Comment by ernestorocha** [comment]
To be honest I already saw that bug, because I've stumble on the same error message. But I couldn't fully understand your discussion with that guy.

If for some reason you can't ensure the same behavior, at least return the newly created object id, somehow.

Just another thing I failed to mention, the code I was trying to run was on the server side.

Thanks in advance!

**Comment by matb33** [comment]
Let me know if you encounter any issues with the fix

**Comment by ernestorocha** [comment]
Thanks a lot! I'll test that later.
