### ISSUE TITLE
Server hooks executing before client hooks

### ISSUE THREAD

**Issue by aramk** [matb33/meteor-collection-hooks#87]
I have an `after.update` hook which modifies some associated collections. It seems these are running firstly on the server and then on the client. Before the client has a chance to run the appropriate code, it seems the doc has already synced the changes from the server, since the changes in the hook have already taken place. This caused my hook to fail an assertion and fail early. The end result is as expected though, but I still get the error logged unintentionally.

To avoid this, I've wrapped my hooks in `if Meteor.isServer`. This gets rid of the issue, but it means the client is now no longer executing the updates in the hook. Since this is only affecting other documents it's not import to run them on the client - they're synced anyway.

For some hooks, I think it's still important to have them run on both the client and server - in particular those which update the doc (e.g. `before.insert`). I'm not sure what would happen if the server doc after the insert was different to the client doc.

I just wanted to mention this in case others experience it.

**Comment by matb33** [comment]
I might be wrong but it sounds like a side-effect of allow/deny. Since the allow/deny logic has to run on the server, the client can't ever run an after.update as a direct result of the original call to update -- it has to be triggered by the sequence of events that allow/deny causes. Once allow/deny has done its work, the server will perform the update, which in turn will push changes via publish. The client would then feel the effects of the after.update.

**Comment by aramk** [comment]
Thanks, that makes sense. From what I can tell from [this answer](http://stackoverflow.com/questions/14547929/meteor-js-allow-deny-rules) the allow rules are only run for the client when posting to the server? But the sequence of events would explain why I'm seeing the client hook executed second. I guess I'll leave all `before` hooks to run on both the client and server to ensure the models are consistent, and any `after` hooks should only run on the server and have their changes sync on the client.
