### ISSUE TITLE
using with upsert

### ISSUE THREAD

**Issue by chrishill627** [matb33/meteor-collection-hooks#88]
I am using upsert for adding documents and updating them. I got an error if I used before.upsert with the package, is it possible to do this?

**Comment by matb33** [comment]
I haven't yet implemented support upsert. No good reason other than me not using upsert in a project yet... but I definitely will implement it for collection-hooks. This serves as a good reminder :)

**Comment by fusepilot** [comment]
Upsert is really useful, so this would be a great to have.

**Comment by jonjamz** [comment]
+1

**Comment by sgtpepper43** [comment]
+1

**Comment by faceyspacey** [comment]
+10

**Comment by matb33** [comment]
I have upsert done but need to write more tests! If anyone wanted to help me with the last mile, it's a great way to get your name into this package! It's all in the upsert branch

**Comment by dmitrijs-balcers** [comment]
+1

**Comment by dmitrijs-balcers** [comment]
@matb33 Can you specify the set of tests that should be written, so the branch would be merged in? I really need hooks for upsert, for the project I'm working in.

**Comment by mizzao** [comment]
I'm confused. Does upsert currently not use any hooks, or does it just use the update and insert hooks in some funny way?

**Comment by rclai** [comment]
Pretty much upserts only work on updates and not on inserts.

**Comment by mizzao** [comment]
b69bfdacba68877311dc6dde0246651522e39f68 suggests that a `before.upsert` hook will always be fired, and an `after.update` *OR* `after.insert` hook fired afterward depending on the outcome. Is that what you would expect to happen?

Is it ever possible to have a `{multi: true}` kind of thing for upsert operations, and if so how would we deal with that?

**Comment by rclai** [comment]
The introduction of explicit upsert hooks kind of makes things more complicated.

Originally, I was expecting it to trigger only the `before.update` hook and then `after.update` or `after.insert` depending on the outcome.

**Comment by matb33** [comment]
When I designed the `upsert` hooks, it only made sense to me that `before.upsert` would be called as opposed to `before.update` -- the operation isn't necessarily going to be an update so having the hook trigger `before.update` seemed unintuitive. The collection API exposes an `upsert` method after all, and the end-user shouldn't have to care how that implementation works, i.e. `update` with `{upsert: true}`.

That's why I introduced a `before.upsert`, as that's as clear as it gets.

As far as tests go, I don't quite recall what I felt was missing.  Also I think the docs need to be updated for upsert.
